# This is sample workflows file created for session
name: first_work
on:
  push: 
    branches: 
      - main
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Execute Single Line
        run: cat /etc/os-release
