# This is sample workflows file created for session

name: first_work
on: 
  push: 
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Execute single lin job
      - run: cat/etc/os-release
    
